stages:
  - clean
  - build
  - deploy

cleanup:
  stage: clean
  script:
    - ./gradlew clean

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug

assembleRelease:
  stage: build
  script:
    - ./gradlew assembleRelease publishToMavenLocal

bintrayUpload:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  when: manual