stages:
  - clean
  - build
  - test
  - publish
  - deploy

cleanup:
  stage: clean
  script:
    - ./gradlew clean

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug

assembleRelease:
  stage: build
  script:
    - ./gradlew assembleRelease

publishToMavenLocal:
  stage: publish
  script:
    - ./gradlew publishToMavenLocal
  dependencies:
    - assembleRelease

bintrayUpload:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - publishToMavenLocal
  when: manual